### ISSUE TITLE
About GPU memory

### ISSUE THREAD

**Issue by hyzl-4869** [bismex/HiCMD#2]
Excuse me.
If my GPU memory is 8，  how can I modify it to make the code run？
Thank you！！

**Comment by bismex** [comment]
Try to reduce the size of input images.
Please find the parameters 'opt.h' and 'opt.w' in the link (https://github.com/bismex/HiCMD/blob/master/set_option.py).

If modifying the above method does not work, reduce the parameter values below. 
- opt.pos_mini_batch
- opt.neg_mini_batch
- opt.samp_pos


However, we do not recommend changing parameters for batch sampling. The performance will not be maintained.
