### ISSUE TITLE
Query regarding KL divergence loss

### ISSUE THREAD

**Issue by chaitrasj** [bismex/HiCMD#4]
Hi,
Thanks for making the code available.
I have a query in the KL divergence loss term, where the KL loss between ID excluded attribute representation  and the Gaussian distribution is tried to be minimised.
Actually I don't understand why is this loss written this way in code, some indices are chosen at att_ex_idx and values at those indices are given to compute_kl method. First, what does those indices signify and second in the compute_kl method, it just computes the mean of the square of the values. 
I also want to add a smiilar loss in my work. Please redirect me to some resource which gives some explanation about the closed form solution for KL divergence between the latent variable and Gaussian distribution.

Thanks a lot in advance!

**Comment by bismex** [comment]
Thank you for your interest in our paper. Our KLD loss encourages the ID-excluded attribute representation to be as close to a prior Gaussian distribution to help the attribute encoder learn more informative representations. For this, I referred to the MUNIT paper, and it is recorded as follows in Chapter 6 of this paper. "the encoded style distributions match their Gaussian priors." And the code for this can be checked through 246, 280~285 lines in the code (https://github.com/NVlabs/MUNIT/blob/master/trainer.py).
